apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: simplr-demo-cluster
  region: us-east-2
vpc:
  id: "vpc-08c54b71caa4efdc9"
  subnets:
    public:
      us-east-2c:
          id: "subnet-06e2e100ebfa9a574"
      us-east-2b:
          id: "subnet-0bbeda2c05f614427"
      us-east-2a:
          id: "subnet-0d291755f72dd5b83"
iam:
  serviceRoleARN: CLUSTER_ROLE_ARN

nodeGroups:
  - name: simplr-demo-nodegroup
    instanceType: t2.micro
    desiredCapacity: 3
    privateNetworking: false
    securityGroups:
      attachIDs: ['sg-0144f9d6e9e718b50']
    iam:
      instanceProfileARN: INSTANCE_PROFILE_ARN
      instanceRoleARN: NODEGROUP_ROLE_ARN
        



# NodeGrpsSecG 
# If you just want to attach extra SGs, you shouldn't need to set withLocal and withShared. These settings are for those who need to use pre-existing SGs only.

# Shared SG is one that we create for all nodegroups, it allows for cluster-wide connectivity between all nodes in all nodegroups. Normally you want to use withShared: true, and it is the default. If you disable it, you isolate the given nodegroup from other nodegroups, unless you use a custom SG that caters for what you need.

# And local SG is one that we create specifically for a given nodegroup only, it is there to control external access as well as access to control plane. E.g. when you enable SSH, the local SG will be were port 22 will be open. Just like withShared, withLocal is enabled by default.

# Hope this makes clearer. As I said above, documentation is needed and help would be hugely appreciated, but we might want to create a new website first, so we can have topical pages.
      


    