apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: simpplr-preprod
  region: us-east-2
vpc:
  id: VPC_ID
  subnets:
    Private:
      AZ1:
          id: SUBNET1
      AZ2:
          id: SUBNET2
      AZ3:
          id: SUBNET3
iam:
  serviceRoleARN: CLUSTER_ROLE_ARN

nodeGroups:
  - name: simpplr-preprod
    instanceType: t2.micro
    desiredCapacity: 3
    privateNetworking: false
    iam:
      instanceProfileARN: INSTANCE_PROFILE_ARN
      instanceRoleARN: NODEGROUP_ROLE_ARN
        