apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: smtip-dev
  region: us-east-1
vpc:
  id: "vpc-014bba1530cf3371d"
  subnets:
    private:
      us-east-1a:
          id: "subnet-079f82f36f4260de1"
      us-east-1b:
          id: "subnet-0a11fbcc96dac3b02"
iam:
  serviceRoleARN: arn:aws:iam::754178572197:role/smtip-cluster-iam-role-dev

nodeGroups:
  - name: smtip-dev
    instanceType: t2.micro
    minSize: 2
    maxSize: 2
    desiredCapacity: 2
    kubeletExtraConfig:
      kubeReserved:
          cpu: "300m"
          memory: "300Mi"
          ephemeral-storage: "1Gi"
      kubeReservedCgroup: "/kube-reserved"
      systemReserved:
          cpu: "300m"
          memory: "300Mi"
          ephemeral-storage: "1Gi"
      evictionHard:
          memory.available:  "200Mi"
          nodefs.available: "10%"
      featureGates:
          DynamicKubeletConfig: true
          RotateKubeletServerCertificate: true # has to be enabled, otherwise it will be disabled
    privateNetworking: true
    iam:
      instanceProfileARN: arn:aws:iam::754178572197:instance-profile/smtip-eks-node-group-instance-profile-dev
      instanceRoleARN: arn:aws:iam::754178572197:role/smtip-nodegroup-iam-role-dev
