apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000
