apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
    - name: backend
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001

