AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates and infra for Netwrok Load Balancer'
# Parameters:
#   vpcid:
#     Description: 'vpcid of the account'
#     Type: String
#     Default: "vpc-08c54b71caa4efdc9"
  # subnets:
  #   Description: 'subnets of the account'
  #   Type: List<AWS::EC2::Subnet::Id>  
  #   Default: ["subnet-06e2e100ebfa9a574","subnet-0bbeda2c05f614427","subnet-0d291755f72dd5b83"]  
Resources:

  SimplrNetworkLoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    DeletionPolicy: Retain
    Properties:
      Name: "simplr-nlb"
      Scheme: "internet-facing"
      Type: network
      Subnets: ["subnet-06e2e100ebfa9a574","subnet-0bbeda2c05f614427","subnet-0d291755f72dd5b83"]

  SimplrNLBTargetGroup: 
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    DeletionPolicy: Retain
    Properties:
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPort: traffic-port
      HealthCheckProtocol: TCP
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      Name: simplr-nlb-tg
      Port: 80
      Protocol: TCP
      VpcId: vpc-08c54b71caa4efdc9
      TargetType: "ip"   

  SimplrNLBListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    DeletionPolicy: Retain
    Properties:
      DefaultActions:
      - TargetGroupArn: !Ref SimplrNLBTargetGroup
        Type: forward
      LoadBalancerArn: !Ref SimplrNetworkLoadBalancer
      Port: 80
      Protocol: TCP
  
  SimplrNLBS3: # cannot be deleted with data
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: "simplr-infra-bucket"
      
  BucketPolicyPublic:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref SimplrNLBS3
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Principal: '*'
          Action: 's3:GetObject'
          Effect: Allow
          Resource: !Sub '${SimplrNLBS3.Arn}/*'

Outputs:
    SimplrNlbARN:
      Description: The ARN for the Network Load Balancer
      Value: !Ref SimplrNetworkLoadBalancer
      Export:
        Name: !Sub "${AWS::StackName}-SimplrNlbARN"
    SimplrNlbTgARN:
      Description: The ARN of the Target group of Network Load Balancer
      Value: !Ref SimplrNLBTargetGroup
      Export:
        Name: !Sub "${AWS::StackName}-SimplrNlbTgARN"
    S3BucketName:
      Description: The Name of the S3 Bucket
      Value: !Ref SimplrNLBS3
      Export:
        Name: !Sub "${AWS::StackName}-S3BucketName"
    