AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates and infra for Netwrok Load Balancer'
Parameters:
  vpcid:
    Description: 'vpcid of the account'
    Type: String
  subnets:
    Description: 'subnets of the account'
    Type: List<AWS::EC2::Subnet::Id>  
  
Resources:

  SimplrNetworkLoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Name: "simplr-nlb"
      Scheme: "internet-facing"
      Type: network
      Subnets: !Ref subnets

  SimplrNLBTargetGroup: 
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPort: traffic-port
      HealthCheckProtocol: TCP
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      Name: simplr-nlb-tg
      Port: 80
      Protocol: TCP
      VpcId: !Ref vpcid
      TargetType: "ip"   

  SimplrNLBListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
      - TargetGroupArn: !Ref SimplrNLBTargetGroup
        Type: forward
      LoadBalancerArn: !Ref SimplrNetworkLoadBalancer
      Port: 80
      Protocol: TCP
  
  SimplrNLBS3: # cannot be deleted with data
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: "simplr-alb-ip-address"
      
  BucketPolicyPublic:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref SimplrNLBS3
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Principal: '*'
          Action: 's3:GetObject'
          Effect: Allow
          Resource: !Sub '${SimplrNLBS3.Arn}/*'

Outputs:
    SimplrNlbARN:
      Description: The ARN for the Network Load Balancer
      Value: !Ref SimplrNetworkLoadBalancer
      Export:
        Name: !Sub "${AWS::StackName}-SimplrNlbARN"
    SimplrNlbTgARN:
      Description: The ARN of the Target group of Network Load Balancer
      Value: !Ref SimplrNLBTargetGroup
      Export:
        Name: !Sub "${AWS::StackName}-SimplrNlbTgARN"
    S3BucketName:
      Description: The Name of the S3 Bucket
      Value: !Ref SimplrNLBS3
      Export:
        Name: !Sub "${AWS::StackName}-S3BucketName"
    