apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "backend-ingress"
spec:
  rules:
    - http:
        paths:
          - path: /frontend
            backend:
              serviceName: "frontend-service"
          - path: /backend
            backend:
              serviceName: "backend-service"
