Parameters:
  enviroment:
    Type: String
    AllowedValues:
      - dev
      - qa
    Description: ENV for roles(devs or qa)

  vpcid:
    Type: String
    Default: ''
    Description: VPC ID

  networkstackname:
    Type: String
    Default: ''
    Description: Network Stack Name

  nlbstackname:
    Type: String
    Default: ''
    Description: NLB Stack Name

Resources:
  VpcLink:
      Type: AWS::ApiGateway::VpcLink
      Properties:
          Description:  !Join [ "-", [ 'VPC link for', !Ref enviroment ] ]
          Name: !Join [ "-", [ 'smtip-vpclink', !Ref enviroment ] ]
          TargetArns:
            Fn::ImportValue:
              !Sub "${nlbstackname}-smtipNlbARN"

  SmtipRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties :
        Body :
            swagger : 2.0
            basePath : /
            schemes :
                - http
        Name : !Join [ "-", [ 'smtip-apigateway', !Ref enviroment ] ]
        Parameters:
            endpointConfigurationTypes: REGIONAL

  SmtipMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      RestApiId: !Ref SmtipRestApi
      ResourceId: !GetAtt
        - SmtipRestApi
        - RootResourceId
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: VPC_LINK
    DependsOn: VpcLink

  SmtipApiDeployment:
      Type: 'AWS::ApiGateway::Deployment'
      Properties:
        RestApiId: !Ref SmtipRestApi
        Description: Smtip Root Resource deployment
        StageName: dev
