AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates and infra for Netwrok Load Balancer'

Parameters:
  enviroment:
    Type: String
    AllowedValues: 
      - dev
      - qa
    Description: ENV for roles(devs or qa)

  vpcid:
    Type: String
    Default: ''
    Description: VPC ID   

  networkstackname:
    Type: String
    Default: ''    
    Description: VPC ID    

Resources:
  smtipNetworkLoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    DeletionPolicy: Delete
    Properties:
      Name:
        !Join [ "-", [ 'smtip-nlb', !Ref enviroment ] ]
      Scheme: "internet-facing"
      Type: network
      Subnets: 
        Fn::Split:
          - ","
          - Fn::ImportValue: 
              !Sub "${vpcid}:ingress-subnet:ids" 
  smtipNLBTargetGroup: 
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    DeletionPolicy: Delete
    Properties:
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPort: traffic-port
      HealthCheckProtocol: TCP
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      Name:
        !Join [ "-", [ 'smtip-nlb-tg', !Ref enviroment ] ]
      Port: 80
      Protocol: TCP
      VpcId:
        Fn::ImportValue:  
            !Sub "${networkstackname}:vpc:id"  
      TargetType: "ip"   

  smtipNLBListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    DeletionPolicy: Delete
    Properties:
      DefaultActions:
      - TargetGroupArn: !Ref smtipNLBTargetGroup
        Type: forward
      LoadBalancerArn: !Ref smtipNetworkLoadBalancer
      Port: 80
      Protocol: TCP
  
  smtipNLBS3: # cannot be deleted with data
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName:
          !Join [ "-", [ 'smtipnlb-s3-bucket', !Ref enviroment ] ]      
      
  BucketPolicyPublic:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref smtipNLBS3
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Principal: '*'
          Action: 's3:GetObject'
          Effect: Allow
          Resource: !Sub '${smtipNLBS3.Arn}/*'

Outputs:
    smtipNlbARN:
      Description: The ARN for the Network Load Balancer
      Value: !Ref smtipNetworkLoadBalancer
      Export:
        Name: !Sub "${AWS::StackName}-smtipNlbARN"
    smtipNlbTgARN:
      Description: The ARN of the Target group of Network Load Balancer
      Value: !Ref smtipNLBTargetGroup
      Export:
        Name: !Sub "${AWS::StackName}-smtipNlbTgARN"
    S3BucketName:
      Description: The Name of the S3 Bucket
      Value: !Ref smtipNLBS3
      Export:
        Name: !Sub "${AWS::StackName}-S3NlbBucketName"    