apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::838660873199:user/deepakdefault
      username: deepakdefault
    - userarn: arn:aws:iam::838660873199:user/deepakkubesystem
      username: deepakkubesystem