apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-default
  namespace: default
subjects:
- kind: User
  name: developer-default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer-default
  apiGroup: rbac.authorization.k8s.io

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testers-kubesystem
  namespace: kubesystem
subjects:
- kind: User
  name: testers-kubesystem
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: testers-kubesystem
  apiGroup: rbac.authorization.k8s.io