kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deepakdefault
  namespace: default
subjects:
- kind: User
  name: deepakdefault
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: deepakdefault
  apiGroup: rbac.authorization.k8s.io
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deepakkubesystem
  namespace: default
subjects:
- kind: User
  name: deepakkubesystem
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: deepakkubesystem
  apiGroup: rbac.authorization.k8s.io
