variable "admin_project" { }
variable "creds" { }
variable "region" { }
variable "node_version" { }
variable "cluster_name_prefix" { }
variable "node_pool_name_prefix" { }
variable "machine_type" { }
variable "image_type" { }
variable "disk_type" { }
variable "disk_size_gb" { }
variable "min_node_count" { }
variable "max_node_count" { }
variable "initial_node_count" { }
variable "max_pods_per_node" { }
variable "disable_legacy_endpoints" { }
variable "cloudflare_email" { }
variable "cloudflare_api_key" { }
variable "cloudflare_zone_id" { }
variable "api_gateway_a_record_name" { }
variable "ops_portal_a_record_name" { }
variable "api_gateway_image_version" { }
variable "ops_portal_image_version" { }
