apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: simplr-demo-cluster
  region: us-east-2
namespace: default
vpc:
  id: "vpc-08c54b71caa4efdc9"
  subnets:
    public:
      us-east-2c:
          id: "subnet-06e2e100ebfa9a574"
      us-east-2b:
          id: "subnet-0bbeda2c05f614427"
      us-east-2a:
          id: "subnet-0d291755f72dd5b83"
iam:
  serviceRoleARN: "arn:aws:iam::838660873199:role/eks-cluster-iamrole"
  
nodeGroups:
  - name: simplr-demo-nodegroup
    instanceType: t2.micro
    desiredCapacity: 1
    privateNetworking: true
    securityGroups:
      attachIDs: ['sg-0144f9d6e9e718b50']


    