apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: simplr-demo-cluster
  region: us-east-2
vpc:
  id: "vpc-08c54b71caa4efdc9"
  subnets:
    public:
      us-east-2c:
          id: "subnet-06e2e100ebfa9a574"
      us-east-2b:
          id: "subnet-0bbeda2c05f614427"
      us-east-2a:
          id: "subnet-0d291755f72dd5b83"
iam:
  serviceRoleARN: "arn:aws:iam::11111:role/eks-base-service-role"

nodeGroups:
  - name: simplr-demo-node-group

    instanceType: t2.micro
    desiredCapacity: 1
    iam:
      instanceProfileARN: "arn:aws:iam::11111:instance-profile/eks-nodes-base-role"
      instanceRoleARN: "arn:aws:iam::1111:role/eks-nodes-base-role"
    privateNetworking: true
    securityGroups:
      withShared: true
      withLocal: true
      attachIDs: ['sg-0144f9d6e9e718b50']